### ISSUE TITLE
Closing vMix craches application

### ISSUE THREAD

**Issue by MartLeib** [dlamon1/listotron#7]
When I close vMix while Listotron is running I get Javascript errors:
![image](https://user-images.githubusercontent.com/31477865/150986800-bcf982cb-0009-4ae0-b58b-8174927dd85f.png)

The same happens when I try to connect to vMix which is not running, I get the following:
![image](https://user-images.githubusercontent.com/31477865/150986968-d401b776-0655-40f2-bc52-a97e3ab1b54f.png)

The only way to get past them is to kill Listotron using task manager.

**Comment by dlamon1** [comment]
Fixed, new version published.
